version: "3.8"

services:
  mongo:
    image: mongo:6
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo:/data/db

  backend:
    build: ./backend
    container_name: backend
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - .env.dev   # veya .env.prod
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    container_name: frontend
    restart: always
    ports:
      - "3002:3002"
    env_file:
      - .env.dev   # veya .env.prod
    depends_on:
      - backend
